config/routes.rb
Rails.application.routes.draw do
  get 'home/show'
  root :to => 'home#show'
  resources :books
  resources :users
  get 'books/:id/issue_book' => 'books#issue_book', as: :issue_book
  put 'books/:id/issue_book_to_user' => 'books#issue_book_to_user', as: :issue_book_to_user
  get 'books/:id/return_book' => 'books#return_book', as: :return_book
  get 'search_book' => 'books#search_book', as: :search_book
  get 'search_book_result' => 'books#search_book_result'
  get 'search_user' => 'users#search_user', as: :search_user
  get 'search_user_result' => 'users#search_user_result'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	validates :title, :presence => true
	validates :title, :uniqueness => true
	validates :author, :presence => true

	def self.fetch_book(title, author)
		where('title =? and author =?', title, author)
	end
end

app/models/user.rb
class User < ApplicationRecord
	has_many :books
	validates :name, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	before_action :set_book, only: [:issue_book_to_user, :return_book]

	def index
	  @books = Book.all
	end

	def new
	  @book = Book.new
	end

	def show
		@book = Book.find(params[:id])
	end

	def create
	  @book = Book.new(book_params)
	  if @book.save
	  	redirect_to books_path, flash: {notice: 'Book was successfully created.'}
	  else
	  	render :new
	  end
	end

	def issue_book; end

	def issue_book_to_user
	  issued_user = User.find_by_name(params[:issued_to])
	  if issued_user
	  	if issued_user.books.count < 3
		    if @book.update_attributes(user_id: issued_user.id, status: 'Issued')
		      redirect_to books_path, flash: {notice: 'Book has been successfully issued.'}
		    else
		      flash[:error] = 'Something went wrong!'
		      render 'issue_book'
		    end
		  else
		  	redirect_to books_path, flash: {error: 'This user has max no of books allowed(3)!'}
		  end
	  else
	    flash[:error] = 'No user found!'
	    render 'issue_book'
	  end
	end

	def return_book
	  if @book.update_attributes(user_id: nil, status: 'Available')
	    redirect_to books_url, flash: {notice: 'Book has successfully been returned.'}
	  else
	    flash[:error] = 'Something went wrong!'
	    redirect_to books_url
	  end
	end

	def search_book;	end

	def search_book_result
		@book = Book.fetch_book(params[:title], params[:author]).first
		if @book
			redirect_to book_path(@book, id: @book.id), flash: {notice: 'Book found!'}
		else
			flash[:error] = 'No book found!'
			render :search_book
		end
	end

	private
  # Use callbacks to share common setup or constraints between actions.
  def set_book
    @book = Book.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def book_params
    params.require(:book).permit(:title, :author, :status)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :set_user, only: [:show]

	def index
	  @users = User.all
	end

	def new
	  @user = User.new
	end

	def show
		@user = User.find(params[:id])
	end

	def create
	  @user = User.new(user_params)
	  if @user.save
	  	redirect_to users_path, flash: {notice: 'User was successfully created.'}
	  else
	  	render :new
	  end
	end

  def search_user

  end

  def search_user_result
		@user = User.find_by_name(params[:name])
		if @user
			redirect_to user_path(@user, id: @user.id), flash: {notice: 'User found!'}
		else
			flash[:error] = 'No user found!'
			render :search_user
		end
	end

	private
	  # Use callbacks to share common setup or constraints between actions.
	  def set_user
	    @user = User.find(params[:id])
	  end

	  # Never trust parameters from the scary internet, only allow the white list through.
	  def user_params
	    params.require(:user).permit(:name)
	  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def current_class?(test_path)
		return 'active' if request.path == test_path
		''
	end
end

app/helpers/books_helper.rb
module BooksHelper
	def book_available?(book)
		book.status.eql?('Available') ? true : false
	end

	def book_issued?(book)
		book.status.eql?('Issued') ? true : false
	end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_form.html.erb
<%= form_with(model: book, local: true) do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :book_title %>
  </div>

  <div class="field">
    <%= form.label :author %>
    <%= form.text_field :author, id: :book_author %>
  </div>

  <%= form.hidden_field :status, value: 'Available' %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/books/index.html.erb
<h1>Books</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Author</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.author %></td>
        <td><%= book.status %></td>
        <td><%= link_to_if book_available?(book), 'Issue Book', issue_book_path(book) %></td>
        <td><%= link_to_if book_issued?(book), 'Return book', return_book_path(book), data: { confirm: 'Sure to return to library?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Book', new_book_path %>

app/views/books/issue_book.html.erb
<%= form_with(url: issue_book_to_user_path, method: :put, local: true) do |form| %>
 <h1>Issued to</h1>
  <div class="field">
    <%= text_field_tag :issued_to %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Back', books_path %>

app/views/books/search_book.html.erb
<h1>Search Book</h1>

<%= form_with(url: search_book_result_path, method: :get, local: true) do |form| %>
  <div class="field">
  	<p>Title</p>
    <%= text_field_tag :title %>
  </div>

  <div class="field">
  	<p>Author</p>
    <%= text_field_tag :author %>
  </div>

  <div class="actions">
    <%= form.submit 'Search' %>
  </div>
<% end %>

app/views/books/search_book_result.html.erb
<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>

<p>
  <strong>Author:</strong>
  <%= @book.author %>
</p>

<%= link_to 'Back', search_book_path %>

app/views/books/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>

<p>
  <strong>Author:</strong>
  <%= @book.author %>
</p>

<%= link_to 'Back', search_book_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>

  <head>
    <title>Library Management System</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'styles', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="styles.css">
    <script src="http://code.jquery.com/jquery-latest.min.js" type="text/javascript"></script>
    <script src="script.js"></script>

    <%= yield :head %>


  </head>
  <body>

  <div id='cssmenu'>
  <ul>
     <li class='<%= current_class?(root_path) %>'><a href='<%= root_path %>'><span>Home</span></a></li>
     <li class='<%= current_class?(books_path) %>'><a href='<%= books_path %>'><span>Manage Books</span></a></li>
     <li class='<%= current_class?(new_user_path) %>'><a href='<%= users_path %>'><span>Manage Users</span></a></li>
     <li class='<%= current_class?(search_book_path) %>'><a href='<%= search_book_path %>'><span>Search Book</span></a></li>
     <li class='<%= current_class?(search_user_path) %> last'><a href='<%= search_user_path %>'><span>Search User</span></a></li>
  </ul>
  </div>
   <% if flash[:notice] %>
  <div id="notice"><%= flash[:notice] %></div>
  <% end %>

  <% if flash[:error] %>
   <div id="warning"><%= flash[:error] %></div>
  <% end %>

  <div class="container">
    <%= yield %>
  </div>

  </body>
</html>
  

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :user_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/index.html.erb
<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Book count</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.books.count %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/search_user.html.erb
<h1>Search User</h1>

<%= form_with(url: search_user_result_path, method: :get, local: true) do |form| %>
  <div class="field">
  	<p>Name</p>
    <%= text_field_tag :name %>
  </div>

  <div class="actions">
    <%= form.submit 'Search' %>
  </div>
<% end %>

app/views/users/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @user.name%>
</p>

<%= link_to 'Back', search_user_path %>